// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
import type { StoryblokAsset, StoryblokMultilink, StoryblokRichtext } from '../storyblok.d.ts';
export interface BlockCareers {
  background_color: number | string;
  headline?: string;
  jobs: (ISbStoryData<Job> | string)[];
  text_color: number | string;
  anchor_id?: string;
  component: "block_careers";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockCarousel {
  slides: (Image | Video)[];
  autoplay?: boolean;
  ratio_mobile: number | string;
  ratio_desktop: number | string;
  component: "block_carousel";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockHero {
  items: (Image | Video)[];
  autoplay?: boolean;
  show_logo?: boolean;
  component: "block_hero";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockMediaGrid {
  items: (GridImage | GridVideo)[];
  ratio_mobile: number | string;
  ratio_desktop: number | string;
  component: "block_media_grid";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockSplit {
  content?: (SplitCarousel | SplitMedia)[];
  ratio_mobile?: number | string;
  ratio_desktop?: number | string;
  michelin_star?: boolean;
  headline?: string;
  text: StoryblokRichtext;
  link_title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  reverse?: boolean;
  reverse_desktop?: boolean;
  background_color?: number | string;
  text_color?: number | string;
  anchor_id?: string;
  component: "block_split";
  _uid: string;
  _editable?: string | undefined;
}

export interface BlockText {
  text: StoryblokRichtext;
  text_alignment: "left" | "center" | "right";
  text_placement: "left" | "center" | "right";
  link_title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  background_color?: number | string;
  text_color?: number | string;
  component: "block_text";
  _uid: string;
  _editable?: string | undefined;
}

export interface CareerItem {
  role: string;
  company: string;
  pdf: StoryblokAsset;
  email: string;
  component: "career_item";
  _uid: string;
  _editable?: string | undefined;
}

export interface GridImage {
  image_mobile?: StoryblokAsset;
  image_desktop: StoryblokAsset;
  title?: string;
  sub_title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "grid_image";
  _uid: string;
  _editable?: string | undefined;
}

export interface GridVideo {
  video_mobile?: StoryblokAsset;
  video_desktop: StoryblokAsset;
  title?: string;
  sub_title?: string;
  link?: Exclude<StoryblokMultilink, {linktype?: "email"} | {linktype?: "asset"}>;
  component: "grid_video";
  _uid: string;
  _editable?: string | undefined;
}

export interface Image {
  image_mobile?: StoryblokAsset;
  image_desktop: StoryblokAsset;
  component: "image";
  _uid: string;
  _editable?: string | undefined;
}

export interface Job {
  brand: number | string;
  department: number | string;
  pdf: StoryblokAsset;
  email: string;
  component: "job";
  _uid: string;
  _editable?: string | undefined;
}

export interface Link {
  title: string;
  subtitle?: string;
  link: Exclude<StoryblokMultilink, {linktype?: "asset"}>;
  hide_on_mobile?: boolean;
  component: "link";
  _uid: string;
  _editable?: string | undefined;
}

export interface LinkGroup {
  title: string;
  links: Link[];
  component: "link_group";
  _uid: string;
  _editable?: string | undefined;
}

export interface Page {
  blocks?: (BlockCareers | BlockCarousel | BlockHero | BlockMediaGrid | BlockSplit | BlockText)[];
  seo_title: string;
  seo_description: string;
  seo_image: StoryblokAsset;
  component: "page";
  _uid: string;
  _editable?: string | undefined;
}

export interface Settings {
  navigation_primary?: (Link | LinkGroup)[];
  navigation_secondary?: (Link | LinkGroup)[];
  footer_navigation?: Link[];
  studio_title?: string;
  studio?: StoryblokRichtext;
  places_title?: string;
  places?: StoryblokRichtext;
  contact_title?: string;
  contact?: StoryblokRichtext;
  component: "settings";
  _uid: string;
  _editable?: string | undefined;
}

export interface SplitCarousel {
  autoplay?: boolean;
  autoplay_duration?: string;
  slides?: unknown[];
  component: "split_carousel";
  _uid: string;
  _editable?: string | undefined;
}

export interface SplitMedia {
  media?: StoryblokAsset;
  component: "split_media";
  _uid: string;
  _editable?: string | undefined;
}

export interface Video {
  video_mobile?: StoryblokAsset;
  video_desktop: StoryblokAsset;
  component: "video";
  _uid: string;
  _editable?: string | undefined;
}

export type ContentType = Job | Page | Settings;
